version: "3"
services:
  # Redis
  db:
    image: redis:5.0-rc5-alpine
    hostname: redis
    ports:
      - "6379:6379"
  # Tomcat1
  tomcat1:
      build: tomcat1
      links:
       # Conexion con redis
        - "db:redis"
  tomcat2:
      build: tomcat2
      links:
        # Conexion con redis
        - "db:redis"
  tomcat3:
      build: tomcat3
      links:
        # Conexion con redis
        - "db:redis"
  httpd:
      build: apache
      ports:
        - "80:80"
        - "1936:1936"
      links:
          # Conexion con instancias del cluster
          - tomcat1
          - tomcat2
          - tomcat3
