db:
  image: redis:5.0-rc5-alpine
  hostname: redis
  ports:
    - "6379:6379"
tomcat1:
    build: tomcat1
    links:
      - "db:redis"
tomcat2:
    build: tomcat2
    links:
      - "db:redis"
tomcat3:
    build: tomcat3
    links:
      - "db:redis"
httpd:
    build: apache-web
    ports:
      - "80:80"
      - "1936:1936"
    links:
        - tomcat1
        - tomcat2
        - tomcat3
